---
 - name: generate locale
   command: "{{ item }}"
   with_items:
     - locale-gen
     - update-locale LANG=de_DE.UTF-8
 - name: enable regenerate ssh service
   service: name=regenerate-ssh.service enabled=yes
